# Generated by Django 3.2.11 on 2022-02-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default='IDR', max_length=256),
        ),
    ]
