# Generated by Django 3.2.11 on 2022-02-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transactions_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
