# Generated by Django 3.2.11 on 2022-01-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='account_id',
            new_name='account',
        ),
    ]
