# Generated by Django 3.2.11 on 2022-01-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
