# Generated by Django 3.2.11 on 2022-01-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20220125_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_id',
            new_name='user',
        ),
    ]
